// <auto-generated />
using System;
using Api.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260119232851_ProdutoAlterado")]
    partial class ProdutoAlterado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Common.Models.CATEGORIA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_CRIACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EMPRESAID")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("USUARIOID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EMPRESAID");

                    b.HasIndex("USUARIOID");

                    b.ToTable("CATEGORIA");
                });

            modelBuilder.Entity("Common.Models.EMPRESA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DATA_CRIACAO_CADASTRO")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DATA_CRIACAO_EMPRESA")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EMPRESA_ATIVA")
                        .HasColumnType("int");

                    b.Property<int>("ENDERECOID")
                        .HasColumnType("int");

                    b.Property<string>("NOME_FANTASIA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RAZAO_SOCIAL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ENDERECOID");

                    b.ToTable("EMPRESA");
                });

            modelBuilder.Entity("Common.Models.ENDERECO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BAIRRO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CIDADE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NUMERO")
                        .HasColumnType("int");

                    b.Property<string>("PAIS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RUA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("ENDERECO");
                });

            modelBuilder.Entity("Common.Models.FUNCIONARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CARGO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DATA_ADMISSAO")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DATA_CRIADO")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DATA_DEMISSAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ENDERECOID")
                        .HasColumnType("int");

                    b.Property<string>("FOTO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NOME_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PERMISSAOID")
                        .HasColumnType("int");

                    b.Property<int>("SENHAID")
                        .HasColumnType("int");

                    b.Property<string>("SOBRENOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("USUARIO_ATIVO")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.HasIndex("ENDERECOID");

                    b.HasIndex("PERMISSAOID");

                    b.HasIndex("SENHAID");

                    b.ToTable("FUNCIONARIO");
                });

            modelBuilder.Entity("Common.Models.HISTORICO_MOVIMENTACOES", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_MOVIMENTACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FUNCIONARIOID")
                        .HasColumnType("int");

                    b.Property<int>("PRODUTOID")
                        .HasColumnType("int");

                    b.Property<int>("QUANTIDADE")
                        .HasColumnType("int");

                    b.Property<int>("TIPO_MOVIMENTACAO")
                        .HasColumnType("int");

                    b.Property<int>("USUARIOID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FUNCIONARIOID");

                    b.HasIndex("PRODUTOID");

                    b.HasIndex("USUARIOID");

                    b.ToTable("HISTORICO_MOVIMENTACOES");
                });

            modelBuilder.Entity("Common.Models.PERMISSAO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NOME_PERMISSAO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("PERMISSAO");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DESCRICAO = "Usuário com permissões administrativas do sistema inteiro.",
                            NOME_PERMISSAO = "Administrador"
                        },
                        new
                        {
                            ID = 2,
                            DESCRICAO = "Usuário com permissões básicas do sistema inteiro.",
                            NOME_PERMISSAO = "Usuário"
                        },
                        new
                        {
                            ID = 3,
                            DESCRICAO = "Usuário com permissões administrativas dentro de uma empresa.",
                            NOME_PERMISSAO = "Responsável"
                        },
                        new
                        {
                            ID = 4,
                            DESCRICAO = "Usuário com permissões básicas dentro de uma empresa.",
                            NOME_PERMISSAO = "Funcionário"
                        });
                });

            modelBuilder.Entity("Common.Models.PRODUTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATIVO")
                        .HasColumnType("int");

                    b.Property<int>("CATEGORIAID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATA_CRIACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EMPRESAID")
                        .HasColumnType("int");

                    b.Property<int>("ESTOQUE_ATUAL")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PRECO")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("USUARIOID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORIAID");

                    b.HasIndex("EMPRESAID");

                    b.HasIndex("USUARIOID");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("Common.Models.SENHA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HASH")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SALT")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("ID");

                    b.ToTable("SENHA");
                });

            modelBuilder.Entity("Common.Models.USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DATA_CRIADO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ENDERECOID")
                        .HasColumnType("int");

                    b.Property<string>("FOTO")
                        .HasColumnType("longtext");

                    b.Property<int?>("FUNCIONARIOID")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NOME_SOCIAL")
                        .HasColumnType("longtext");

                    b.Property<int>("PERMISSAOID")
                        .HasColumnType("int");

                    b.Property<int>("SENHAID")
                        .HasColumnType("int");

                    b.Property<string>("SOBRENOME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TELEFONE")
                        .HasColumnType("longtext");

                    b.Property<bool>("USUARIO_ATIVO")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.HasIndex("ENDERECOID");

                    b.HasIndex("FUNCIONARIOID");

                    b.HasIndex("PERMISSAOID");

                    b.HasIndex("SENHAID");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("Common.Models.CATEGORIA", b =>
                {
                    b.HasOne("Common.Models.EMPRESA", "EMPRESA")
                        .WithMany()
                        .HasForeignKey("EMPRESAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.USUARIO", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EMPRESA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Common.Models.EMPRESA", b =>
                {
                    b.HasOne("Common.Models.ENDERECO", "ENDERECO")
                        .WithMany()
                        .HasForeignKey("ENDERECOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ENDERECO");
                });

            modelBuilder.Entity("Common.Models.FUNCIONARIO", b =>
                {
                    b.HasOne("Common.Models.ENDERECO", "ENDERECO")
                        .WithMany()
                        .HasForeignKey("ENDERECOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.PERMISSAO", "PERMISSAO")
                        .WithMany()
                        .HasForeignKey("PERMISSAOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.SENHA", "SENHA")
                        .WithMany()
                        .HasForeignKey("SENHAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ENDERECO");

                    b.Navigation("PERMISSAO");

                    b.Navigation("SENHA");
                });

            modelBuilder.Entity("Common.Models.HISTORICO_MOVIMENTACOES", b =>
                {
                    b.HasOne("Common.Models.FUNCIONARIO", "FUNCIONARIO")
                        .WithMany()
                        .HasForeignKey("FUNCIONARIOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.PRODUTO", "PRODUTO")
                        .WithMany()
                        .HasForeignKey("PRODUTOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.USUARIO", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FUNCIONARIO");

                    b.Navigation("PRODUTO");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Common.Models.PRODUTO", b =>
                {
                    b.HasOne("Common.Models.CATEGORIA", "CATEGORIA")
                        .WithMany()
                        .HasForeignKey("CATEGORIAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.EMPRESA", "EMPRESA")
                        .WithMany()
                        .HasForeignKey("EMPRESAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.USUARIO", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CATEGORIA");

                    b.Navigation("EMPRESA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Common.Models.USUARIO", b =>
                {
                    b.HasOne("Common.Models.ENDERECO", "ENDERECO")
                        .WithMany()
                        .HasForeignKey("ENDERECOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.FUNCIONARIO", "FUNCIONARIO")
                        .WithMany()
                        .HasForeignKey("FUNCIONARIOID");

                    b.HasOne("Common.Models.PERMISSAO", "PERMISSAO")
                        .WithMany()
                        .HasForeignKey("PERMISSAOID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Models.SENHA", "SENHA")
                        .WithMany()
                        .HasForeignKey("SENHAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ENDERECO");

                    b.Navigation("FUNCIONARIO");

                    b.Navigation("PERMISSAO");

                    b.Navigation("SENHA");
                });
#pragma warning restore 612, 618
        }
    }
}
