// <auto-generated />
using System;
using Api.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.CATEGORIA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_CRIACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EMPRESA_ID")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("USUARIO_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EMPRESA_ID");

                    b.HasIndex("USUARIO_ID");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("Api.Models.EMPRESA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("DATA_CRIACAO_CADASTRO")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DATA_CRIACAO_EMPRESA")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EMPRESA_ATIVA")
                        .HasColumnType("int");

                    b.Property<int>("ENDERECO_ID")
                        .HasColumnType("int");

                    b.Property<string>("NOME_FANTASIA")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RAZAO_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ENDERECO_ID");

                    b.ToTable("EMPRESA", (string)null);
                });

            modelBuilder.Entity("Api.Models.ENDERECO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BAIRRO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("CIDADE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("NUMERO")
                        .HasColumnType("int");

                    b.Property<string>("PAIS")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RUA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.ToTable("ENDERECO", (string)null);
                });

            modelBuilder.Entity("Api.Models.FUNCIONARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CARGO")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DATA_ADMISSAO")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DATA_CRIADO")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DATA_DEMISSAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ENDERECO_ID")
                        .HasColumnType("int");

                    b.Property<string>("FOTO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NOME_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PERMISSAO_ID")
                        .HasColumnType("int");

                    b.Property<int>("SENHA_ID")
                        .HasColumnType("int");

                    b.Property<string>("SOBRENOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("USUARIO_ATIVO")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.HasIndex("ENDERECO_ID");

                    b.HasIndex("PERMISSAO_ID");

                    b.HasIndex("SENHA_ID");

                    b.ToTable("FUNCIONARIO", (string)null);
                });

            modelBuilder.Entity("Api.Models.HISTORICO_MOVIMENTACOES", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DATA_MOVIMENTACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FUNCIONARIO_ID")
                        .HasColumnType("int");

                    b.Property<int>("PRODUTO_ID")
                        .HasColumnType("int");

                    b.Property<int>("QUANTIDADE")
                        .HasColumnType("int");

                    b.Property<int>("TIPO_MOVIMENTACAO")
                        .HasColumnType("int");

                    b.Property<int>("USUARIO_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FUNCIONARIO_ID");

                    b.HasIndex("PRODUTO_ID");

                    b.HasIndex("USUARIO_ID");

                    b.ToTable("HISTORICO_MOVIMENTACOES", (string)null);
                });

            modelBuilder.Entity("Api.Models.PERMISSAO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NOME_PERMISSAO")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("PERMISSAO", (string)null);
                });

            modelBuilder.Entity("Api.Models.PRODUTO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ATIVO")
                        .HasColumnType("int");

                    b.Property<int>("CATEGORIA_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATA_CRIACAO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DESCRICAO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EMPRESA_ID")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("PRECO")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("USUARIO_ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CATEGORIA_ID");

                    b.HasIndex("EMPRESA_ID");

                    b.HasIndex("USUARIO_ID");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("Api.Models.SENHA", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("HASH")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SALT")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.HasKey("ID");

                    b.ToTable("SENHA", (string)null);
                });

            modelBuilder.Entity("Api.Models.USUARIO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("DATA_CRIADO")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ENDERECO_ID")
                        .HasColumnType("int");

                    b.Property<string>("FOTO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FUNCIONARIO_ID")
                        .HasColumnType("int");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NOME_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PERMISSAO_ID")
                        .HasColumnType("int");

                    b.Property<int>("SENHA_ID")
                        .HasColumnType("int");

                    b.Property<string>("SOBRENOME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("USUARIO_ATIVO")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.HasIndex("ENDERECO_ID");

                    b.HasIndex("FUNCIONARIO_ID");

                    b.HasIndex("PERMISSAO_ID");

                    b.HasIndex("SENHA_ID");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("Api.Models.CATEGORIA", b =>
                {
                    b.HasOne("Api.Models.EMPRESA", "EMPRESA")
                        .WithMany()
                        .HasForeignKey("EMPRESA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.USUARIO", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EMPRESA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.Models.EMPRESA", b =>
                {
                    b.HasOne("Api.Models.ENDERECO", "ENDERECO")
                        .WithMany()
                        .HasForeignKey("ENDERECO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ENDERECO");
                });

            modelBuilder.Entity("Api.Models.FUNCIONARIO", b =>
                {
                    b.HasOne("Api.Models.ENDERECO", "ENDERECO")
                        .WithMany()
                        .HasForeignKey("ENDERECO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.PERMISSAO", "PERMISSAO")
                        .WithMany()
                        .HasForeignKey("PERMISSAO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.SENHA", "SENHA")
                        .WithMany()
                        .HasForeignKey("SENHA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ENDERECO");

                    b.Navigation("PERMISSAO");

                    b.Navigation("SENHA");
                });

            modelBuilder.Entity("Api.Models.HISTORICO_MOVIMENTACOES", b =>
                {
                    b.HasOne("Api.Models.FUNCIONARIO", "FUNCIONARIO")
                        .WithMany()
                        .HasForeignKey("FUNCIONARIO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.PRODUTO", "PRODUTO")
                        .WithMany()
                        .HasForeignKey("PRODUTO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.USUARIO", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FUNCIONARIO");

                    b.Navigation("PRODUTO");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.Models.PRODUTO", b =>
                {
                    b.HasOne("Api.Models.CATEGORIA", "CATEGORIA")
                        .WithMany()
                        .HasForeignKey("CATEGORIA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.EMPRESA", "EMPRESA")
                        .WithMany()
                        .HasForeignKey("EMPRESA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.USUARIO", "USUARIO")
                        .WithMany()
                        .HasForeignKey("USUARIO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CATEGORIA");

                    b.Navigation("EMPRESA");

                    b.Navigation("USUARIO");
                });

            modelBuilder.Entity("Api.Models.USUARIO", b =>
                {
                    b.HasOne("Api.Models.ENDERECO", "ENDERECO")
                        .WithMany()
                        .HasForeignKey("ENDERECO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.FUNCIONARIO", "FUNCIONARIO")
                        .WithMany()
                        .HasForeignKey("FUNCIONARIO_ID");

                    b.HasOne("Api.Models.PERMISSAO", "PERMISSAO")
                        .WithMany()
                        .HasForeignKey("PERMISSAO_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.SENHA", "SENHA")
                        .WithMany()
                        .HasForeignKey("SENHA_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ENDERECO");

                    b.Navigation("FUNCIONARIO");

                    b.Navigation("PERMISSAO");

                    b.Navigation("SENHA");
                });
#pragma warning restore 612, 618
        }
    }
}
